spring.application.name=LibraryManager
spring.datasource.url= jdbc:postgresql://localhost:5432/libraryManagementDb
spring.datasource.username=postgres
spring.datasource.password=Sql@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect